<?php

/**
 * @file
 * Contains block_date.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_date_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_date module.
    case 'help.page.block_date':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('define a date block condition') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_date_theme() {
  return [
    'block_date' => [
      'render element' => 'children',
    ],
  ];
}
